            - ชื่อ: การดำเนินการเมตาเดต้าของ Docker
  # คุณสามารถกำหนด commit หรือเวอร์ชันที่แน่นอนได้
  # การใช้งาน: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
  ใช้: docker/metadata-action@v5.10.0
  กับ:
    # แหล่งที่มาของข้อมูลบริบท ตัวเลือกที่อนุญาตคือ "workflow" (ค่าเริ่มต้น) และ "git"
    บริบท: # ค่าเริ่มต้นคือเวิร์กโฟลว์
    # รายชื่ออิมเมจ Docker ที่จะใช้เป็นชื่อพื้นฐานสำหรับแท็ก
    รูปภาพ: # ไม่บังคับ
    # รายการแท็กในรูปแบบคู่คีย์-ค่า
    แท็ก: # ตัวเลือกเสริม
    # รสชาติที่สามารถนำไปใช้ได้
    รสชาติ: # เลือกได้
    # รายชื่อป้ายกำกับแบบกำหนดเอง
    ป้ายกำกับ: # ตัวเลือกเสริม
    # รายการคำอธิบายประกอบแบบกำหนดเอง
    คำอธิบายประกอบ: # ไม่บังคับ
    # ตัวคั่นที่ใช้สำหรับการแสดงผลแท็ก (ค่าเริ่มต้นคือ \n)
    sep-tags: # ตัวเลือกเสริม
    # ตัวคั่นที่ใช้สำหรับแสดงผลป้ายกำกับ (ค่าเริ่มต้นคือ \n)
    ป้ายกำกับแยก: # ตัวเลือกเสริม
    # ตัวคั่นที่ใช้สำหรับการแสดงผลคำอธิบายประกอบ (ค่าเริ่มต้นคือ \n)
    คำอธิบายประกอบแยก: # ไม่บังคับ
    # ตั้งชื่อเป้าหมายสำหรับการสร้างไฟล์ (ค่าเริ่มต้นคือ docker-metadata-action)
    เป้าหมายการอบ: # ตัวเลือกเสริม
    # โทเค็น GitHub ที่ได้รับจาก secrets
    github-token: # ค่าเริ่มต้นคือ ${{ github.token }}
          
