            - ชื่อ: ดาวน์โหลดไฟล์สร้าง (Build Artifact)
  ใช้: actions/download-artifact@v7.0.0
  กับ:
    # ชื่อของไฟล์ที่จะดาวน์โหลด หากไม่ได้ระบุ ระบบจะดาวน์โหลดไฟล์ทั้งหมดสำหรับการดำเนินการนั้น
    ชื่อ: # (ไม่บังคับ)
    # รหัสของไฟล์ที่จะดาวน์โหลด คั่นด้วยเครื่องหมายจุลภาค สามารถใช้ได้ทั้ง `artifact-ids` หรือ `name` อย่างใดอย่างหนึ่ง แต่ห้ามใช้ทั้งสองอย่างพร้อมกัน
    รหัสสิ่งประดิษฐ์: # ไม่บังคับ
    # เส้นทางปลายทาง รองรับการขยายด้วยเครื่องหมายทิลเดพื้นฐาน ค่าเริ่มต้นคือ $GITHUB_WORKSPACE
    เส้นทาง: # ไม่บังคับ
    # รูปแบบ glob ที่ตรงกับไฟล์ที่ควรดาวน์โหลด จะถูกละเว้นหากระบุชื่อไฟล์ไว้แล้ว
    รูปแบบ: # ตัวเลือกเสริม
    # เมื่อมีการจับคู่ไฟล์หลายไฟล์ การตั้งค่านี้จะเปลี่ยนแปลงพฤติกรรมของไดเร็กทอรีปลายทาง หากเป็นจริง ไฟล์ที่ดาวน์โหลดจะอยู่ในไดเร็กทอรีเดียวกันกับที่ระบุโดยพาธ หากเป็นเท็จ ไฟล์ที่ดาวน์โหลดจะถูกแยกออกเป็นไดเร็กทอรีที่มีชื่อแต่ละรายการภายในพาธที่ระบุ
    merge-multiple: # ตัวเลือกเสริม ค่าเริ่มต้นคือ false
    # โทเค็น GitHub ที่ใช้ในการยืนยันตัวตนกับ GitHub API จำเป็นต้องใช้เมื่อดาวน์โหลดไฟล์จากที่เก็บข้อมูลอื่นหรือจากเวิร์กโฟลว์ที่ทำงานต่างกัน หากไม่ได้ระบุไว้ การดำเนินการจะพยายามดาวน์โหลดไฟล์จากที่เก็บข้อมูลปัจจุบันและเวิร์กโฟลว์ที่ทำงานปัจจุบัน
    โทเค็น GitHub: # ไม่บังคับ
    # ชื่อเจ้าของ repository และชื่อ repository ที่เชื่อมต่อกันด้วยเครื่องหมาย "/" หากระบุ github-token ไว้ นี่คือ repository ที่จะดาวน์โหลดไฟล์ artifacts ออกมา
    repository: # ไม่บังคับ ค่าเริ่มต้นคือ ${{ github.repository }}
    # รหัสของการทำงานของเวิร์กโฟลว์ที่อัปโหลดไฟล์ดาวน์โหลดที่ต้องการ หากระบุ github-token ไว้ จะเป็นการทำงานของเวิร์กโฟลว์ที่จะใช้ดาวน์โหลดไฟล์
    run-id: # ไม่บังคับ ค่าเริ่มต้นคือ ${{ github.run_id }}
          
