            - ชื่อ: หัวหน้าเจ้าหน้าที่พิทักษ์
  # คุณสามารถกำหนด commit หรือเวอร์ชันที่แน่นอนได้
  # ใช้: Ispx/Main-Guardian@03dcc92349ed3b21b3eb4c0d27b1e63d1a9ff512
  ใช้: Ispx/Main-Guardian@v1.0.4
  กับ:
    # คีย์ API สำหรับ Google Gemini
    คีย์ API ของเจมินี:
    # โทเค็น GitHub สำหรับการโพสต์ความคิดเห็นและการตรวจสอบโค้ด ค่าเริ่มต้นคือ github.token
    github-token: # ค่าเริ่มต้นคือ ${{ github.token }}
          
